### ISSUE TITLE
How are we supposed to use the mod if the latest BFAPI version for download is 1.1.0?

### ISSUE THREAD

**Issue by zoomed-bepis** [BradBot1/LifeSteal#1]
I tried using this mod on my server but when I tried to start I needed BFAPI 1.1.8, but if we go to the Github page for BFAPI we see that the latest version is 1.1.0...what are we supposed to do? I was thinking about just changing the version by editing some files.

**Comment by BradBot1** [comment]
Modrinth or curseforge, they are available at the bottom of the README.md file
