### ISSUE TITLE
Is The Code Useable?

### ISSUE THREAD

**Issue by PixelDev990** [BradBot1/LifeSteal#4]
I know this isnt a issue
But i'd like to know if i can use your code to develop a plugin for a upcoming youtuber smp named "Heartfuse SMP" 
Now ofc you will be given credit so dont worry about that

**Comment by BradBot1** [comment]
As long as you follow the license terms and credit me somewhere visible (like the README) you can use it however you wish

**Comment by PixelDev990** [comment]
alr

**Comment by PixelDev990** [comment]
it is private fyi

**Comment by PixelDev990** [comment]
but sure

**Comment by BradBot1** [comment]
That doesn't matter, as long as its on the private page it's all good
